version: "3.7"

services:
  crown-clothing-api:
    container_name: frontend
    build: ./
    command: yarn start
    working_dir: /usr/src/crwn-clothing
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/crwn-clothing
